-- begin ACCOUNT_CATEGORY
create unique index IDX_ACCOUNT_CATEGORY_UNIQ_NAME on ACCOUNT_CATEGORY (NAME) where DELETE_TS is null ^
-- end ACCOUNT_CATEGORY
-- begin ACCOUNT_PRODUCT
alter table ACCOUNT_PRODUCT add constraint FK_ACCOUNT_PRODUCT_CATEGORY_ID foreign key (CATEGORY_ID) references ACCOUNT_CATEGORY(ID)^
create unique index IDX_ACCOUNT_PRODUCT_UNIQ_NAME on ACCOUNT_PRODUCT (NAME) where DELETE_TS is null ^
create index IDX_ACCOUNT_PRODUCT_CATEGORY on ACCOUNT_PRODUCT (CATEGORY_ID)^
-- end ACCOUNT_PRODUCT

-- begin ACCOUNT_BILL
alter table ACCOUNT_BILL add constraint FK_ACCOUNT_BILL_SHOP_ID foreign key (SHOP_ID) references ACCOUNT_SHOP(ID)^
create index IDX_ACCOUNT_BILL_SHOP on ACCOUNT_BILL (SHOP_ID)^
-- end ACCOUNT_BILL
-- begin ACCOUNT_BILL_ITEM
alter table ACCOUNT_BILL_ITEM add constraint FK_ACCOUNT_BILL_ITEM_BILL_ID foreign key (BILL_ID) references ACCOUNT_BILL(ID)^
alter table ACCOUNT_BILL_ITEM add constraint FK_ACCOUNT_BILL_ITEM_PRODUCT_ID foreign key (PRODUCT_ID) references ACCOUNT_PRODUCT(ID)^
alter table ACCOUNT_BILL_ITEM add constraint FK_ACCOUNT_BILL_ITEM_BRAND_ID foreign key (BRAND_ID) references ACCOUNT_BRAND(ID)^
create index IDX_ACCOUNT_BILL_ITEM_PRODUCT on ACCOUNT_BILL_ITEM (PRODUCT_ID)^
create index IDX_ACCOUNT_BILL_ITEM_BRAND on ACCOUNT_BILL_ITEM (BRAND_ID)^
create index IDX_ACCOUNT_BILL_ITEM_BILL on ACCOUNT_BILL_ITEM (BILL_ID)^
-- end ACCOUNT_BILL_ITEM
-- begin ACCOUNT_BRAND
create unique index IDX_ACCOUNT_BRAND_UNIQ_NAME on ACCOUNT_BRAND (NAME) where DELETE_TS is null ^
-- end ACCOUNT_BRAND
