-- begin ACCOUNT_PRODUCT

create unique index IDX_ACCOUNT_PRODUCT_UNIQ_NAME on ACCOUNT_PRODUCT (NAME) where DELETE_TS is null ^
-- end ACCOUNT_PRODUCT


-- begin ACCOUNT_BILL
alter table ACCOUNT_BILL add constraint FK_ACCOUNT_BILL_PRODUCT_ID foreign key (PRODUCT_ID) references ACCOUNT_PRODUCT(ID)^

create index IDX_ACCOUNT_BILL_PRODUCT on ACCOUNT_BILL (PRODUCT_ID)^

-- end ACCOUNT_BILL
